name: 'iisftp'
description: 'Create public keys and sftp folder mappings in the integration platform client'
inputs:
  integrations-config:
    description: 'Configuration'
    required: yes
  flags:
    description: '--dry-run|--insecure/-k|--output-format <json|yaml>/-o|--logs/-l|-d/--data "[changed-files]"'
    required: no
outputs:
  logs:
    description: 'Result of the process execution'
runs:
  using: 'docker'
  image: 'docker://fdn-sre-docker-dev.mia.ulti.io/tip/iisftp:latest'
  env:
    INTEGRATIONS_CONFIG: ${{inputs.integrations-config}}
  args:
    - ${{inputs.flags}}
branding:
  icon: 'folder-plus'
  color: 'green'
